version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg_course
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d course_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  flyway:
    image: flyway/flyway
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "migrate"
      - "-baselineOnMigrate=true"
      - "-connectRetries=60"
    volumes:
      - ./db/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/course_db
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: admin_pass
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: public

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data: